package com.codename1.demos.imagegallery;

import static com.codename1.ui.CN.*;

import com.codename1.components.ScaleImageLabel;
import com.codename1.ext.imagegallery.ImageGallery;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class ImageGalleryDemo extends Lifecycle {

    private Container photoFrame;

    public void init(Object context) {
        super.init(context);
        if (ImageGallery.isSupported()) {
            ImageGallery.register();
        }
    }

    @Override
    public void runApp() {
        Form hi = new Form("Hi World", BoxLayout.y());
        photoFrame = new Container(new BorderLayout());
        hi.add(photoFrame);
        Button openGallery = new Button("Select Image...");
        ButtonGroup typeGroup = new ButtonGroup();
        RadioButton typeImage = new RadioButton("Image");
        RadioButton typeVideo = new RadioButton("Video");
        RadioButton typeAll = new RadioButton("All");
        typeGroup.add(typeImage);
        typeGroup.add(typeVideo);
        typeGroup.add(typeAll);


        CheckBox multi = new CheckBox("Multi Select");
        hi.add(openGallery);
        hi.add(FlowLayout.encloseCenter(typeImage, typeVideo, typeAll));
        hi.add(FlowLayout.encloseCenter(multi));
        openGallery.addActionListener(e -> {
            int type = typeImage.isSelected()
                    ? (multi.isSelected() ? Display.GALLERY_IMAGE_MULTI : Display.GALLERY_IMAGE)
                    : typeVideo.isSelected()
                            ? (multi.isSelected() ? Display.GALLERY_VIDEO_MULTI : Display.GALLERY_VIDEO)
                            : (multi.isSelected() ? Display.GALLERY_ALL_MULTI : Display.GALLERY_ALL);
            openImageGallery(type);
        });

        hi.show();
    }



    private void openImageGallery(int type) {
        Display.getInstance().openGallery((e) -> {

            if(e != null && e.getSource() != null) {
                Log.p("Selected: " + e.getSource());
                String[] files = isMulti(type) ? (String[])e.getSource() : new String[]{(String)e.getSource()};
                photoFrame.removeAll();
                photoFrame.setLayout(BoxLayout.y());


                for (String file : files) {
                    try {
                        Image img = Image.createImage(file);
                        // do something with the image...
                        photoFrame.add(new ScaleImageLabel(img));

                    } catch(Exception ex) {
                        Log.e(ex);
                    }
                }
                photoFrame.getComponentForm().revalidate();

            }
        }, type);
    }

    private boolean isMulti(int type) {
        switch (type) {
            case Display.GALLERY_ALL_MULTI:
            case Display.GALLERY_IMAGE_MULTI:
            case Display.GALLERY_VIDEO_MULTI:
                return true;
            default:
                return false;
        }
    }

}
